### ISSUE TITLE
Error when upolading a file

### ISSUE THREAD

**Issue by Syauri** [NLPbox/rstweb-service#1]
I am getting the following error when trying to import a file:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "start_local_docker.py", line 79, in admin
    return admin_main("local","3",'local',**kwargs)
  File "/opt/rstweb/admin.py", line 378, in admin_main
    fail = import_plaintext(importdir + fn,imp_project,user,rel_hash,do_tokenize=do_tokenize)
  File "/opt/rstweb/modules/rstweb_sql.py", line 279, in import_plaintext
    cur.execute("INSERT INTO rst_signal_types VALUES(?,?,?,?)",
NameError: global name 'cur' is not defined

I am assuming it is because I don't have python2.7 folder and I am using mac Catalina. Is there a way to work around this problem?

**Comment by arne-cl** [comment]
Dear @Syauri,

please let me know how you installed/run the software. 
Did you use ``docker run -p 9000:8080 -ti nlpbox/rstweb-service``?
How did you upload the file?
